 puml 
@startuml
'https://plantuml.com/class-diagram

package XMLSchema {
    class int{}
    class string{}
    class boolean{}
}

package OurGame{
    
    class Jeu{
        plateau : Plateau
        joueur1 : Joueur
        joueur2 : Joueur
    }
    
    class Plateau { 
        map : TabInvocation[]
    }
    
    class TabInvocation {
        tab :  Invocation[]
    }
    
    
    class Joueur {
        pseudo : string
        winStreak : int
        jauge : int
        main : ListeDeCartes
        deck : ListeDeCartes
    }
    
    class ListeDeCartes {
        carte : Carte[]
    }
    
    class Carte {
        vie : int
        degat : int
        nom : string
        image : string 
        cout : int
        type : TypeDeCarte
        invocation : Invocation
        rarete : TypeRarete
        
    }
    
    class TypeDeCarte <<enum>> {
        combattant
        sort
        objet
    }
    
    class TypeRarete <<enum>> {
        commune
        rare
        épique
        légendaire
    }
    
    class Invocation {
        vie : int
        degat : int
        pseudoInvocateur : string
        estJouable : boolean
    }
    
    
    Jeu *-- Plateau
    Jeu "1"*--"2" Joueur
    TabInvocation "1"*--"*" Invocation
    Joueur "1"*--"2" ListeDeCartes
    ListeDeCartes "1"*--"*" Carte
    Carte *-- TypeDeCarte
    Carte *-- Invocation
    Carte *-- TypeRarete
    Invocation *-- Joueur
    Plateau "1"*--"*" TabInvocation 
}
@enduml